spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    log-resolved-exception: false

dutypark:
  slack:
    token: ""
    channel: "error-log"

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: "key_password_here"
    key-store-type: PKCS12
    enabled: true
